apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: comments
  template:
    metadata:
      labels:
        apps: comments
    spec:
      containers:
      - name: comments
        image: ibro2002/comments:latest
        # ports:
        #   - containerPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: comments-service
spec:
  selector:
    apps: comments
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001