apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: moderation
  template:
    metadata:
      labels:
        apps: moderation
    spec:
      containers:
      - name: moderation
        image: ibro2002/moderation:latest
        # ports:
          # - containerPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-service
spec:
  selector:
    apps: moderation
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003